name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -qq install python-nfqueue
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose
        python setup.py install
    - name: Run the tests
      run: |
        nosetests -v
